### ISSUE TITLE
Hepsiburada npm Registry Error

### ISSUE THREAD

**Issue by fatihtelis** [hepsiburada/VoltranJS-Starter-Kit#1]
voltranjs has subdependencies like "@voltran/common" which is only available on hepsiburada npm registry (npm.hepsiburada.com). Since this is not a public registry, it is impossible to install node_modules if you don't have access to npm.hepsiburada.com.

When you try to install the packages, it gives the following error. I couldn't install the package even I delete the yarn.lock file.

`error Couldn't find package "@voltran/common@^1.0.13" required by "voltranjs@^1.0.0" on the "npm" registry.`

Here is the related part in yarn.lock file.

```
"@voltran/common@^1.0.13":
  version "1.0.13"
  resolved "http://npm.hepsiburada.com/@voltran%2fcommon/-/common-1.0.13.tgz#18ef1efe41a3ef566f1e2f8ba825d4157cbfef61"
```

**Comment by yasinatesim** [comment]
Thank you for feedback 😉  This issue is resolved.
